name: Terraform Format

on:
  workflow_call:
    inputs:
      parent_tf_dir:
        required: true
        type: string
        description: Parent directory where all Terraform files are underneath
        default: "."
      cli_opts:
        required: false
        type: string
        default: " "

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Setup Nodejs
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: lts/*
          check-latest: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          cli_config_credentials_token: AAA
      - name: Terraform Format
        run: |
          cd $TF_DIR
          terraform fmt -recursive -check ${{ inputs.cli_opts }} .
